# Visualisation

mesh_files:
  base:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/base.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/base.stl
    mesh_offset:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: !degrees 180

  shoulder:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/shoulder.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/shoulder.stl
    mesh_offset:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: !degrees 180

  upper_arm:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/upperarm.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/upperarm.stl
      mesh_files:
    mesh_offset:
      x: 0.0
      y: 0.0
      z: 0.120
      roll: !degrees 90
      pitch: 0.0
      yaw: !degrees -90

  forearm:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/forearm.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/forearm.stl
    mesh_offset:
      x: 0.0
      y: 0.0
      z: 0.027
      roll: !degrees 90
      pitch: 0.0
      yaw: !degrees -90

  wrist_1:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/wrist1.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/wrist1.stl
    visual_offset: -0.104
    mesh_offset:
      x: 0.0
      y: 0.0
      z: -0.104
      roll: !degrees 90
      pitch: 0.0
      yaw: 0.0

  wrist_2:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/wrist2.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/wrist2.stl
    visual_offset: -0.08535
    mesh_offset:
      x: 0.0
      y: 0.0
      z: -0.08535
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

  wrist_3:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/wrist3.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/wrist3.stl
    visual_offset_xyz: 0 0 -0.0921
    visual_offset: -0.0921
    mesh_offset:
      x: 0.0
      y: 0.0
      z: -0.0921
      roll: !degrees 90
      pitch: 0.0
      yaw: 0.0