mesh_files:
  base:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/base.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/base.stl

  shoulder:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/shoulder.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/shoulder.stl

  upper_arm:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/upperarm.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/upperarm.stl
      mesh_files:

  forearm:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/forearm.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/forearm.stl

  wrist_1:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/wrist1.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/wrist1.stl
    visual_offset: -0.127

  wrist_2:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/wrist2.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/wrist2.stl
    visual_offset: -0.0997

  wrist_3:
    visual:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/visual/wrist3.dae
    collision:
      mesh:
        package: arm_mine_explorer_description
        path: meshes/collision/wrist3.stl
    visual_offset: -0.0989
