slam_toolbox:
  ros__parameters:

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /sensors/lidar/scan_2d
    mode: mapping
    
    max_laser_range: 20.0
    minimum_time_interval: 0.1
    transform_timeout: 0.8
    tf_buffer_duration: 30.0
    transform_publish_period: 0.05
    map_update_interval: 1.0

    resolution: 0.05
    
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    distance_variance_penalty: 1.0
    angle_variance_penalty: 1.0

    correlation_threshold: 0.5
    huber_limit: 0.1

    do_loop_closure: true
    loop_search_distance: 10.0
    use_odom_multi_level_mapper: true